### PR TITLE
Created MIT License

### PR DESCRIPTION
**Pull request by Nathan-Nesbitt**
I will ask that everyone approves or rejects the following pull request through comment or through review approval/rejection to show that they approve/reject the following changes:

    The project will now be licensed under the MIT license.

The MIT license is shown in the changes in this pull request.

### CODE REVIEW

**Review by kzlecha — APPROVED** [review]
Looks good. Go ahead

**Review by laurenstclair — COMMENTED** [review]
Looks good

**Comment by Nathan-Nesbitt** [comment]
@emedema  thoughts?

**Comment by emedema** [comment]
Looks good!

**Pull request merged**
